/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p.f.e;

import javax.swing.JFileChooser;

/**
 *
 * @author YACIN
 */
public class predictionDesLiens extends javax.swing.JFrame {

    /**
     * Creates new form predictionDesLiens
     */
    public predictionDesLiens() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        m5 = new javax.swing.JRadioButton();
        m10 = new javax.swing.JRadioButton();
        lens = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        displayPath = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        adamic = new javax.swing.JRadioButton();
        attach = new javax.swing.JRadioButton();
        jaccard = new javax.swing.JRadioButton();
        power = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Jeux de données", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 14))); // NOI18N

        buttonGroup1.add(m5);
        m5.setText("Matrice 5x5");

        buttonGroup1.add(m10);
        m10.setText("Matrice 10x10");

        buttonGroup1.add(lens);
        lens.setText("MovieLens");

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPath)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m5)
                            .addComponent(m10)
                            .addComponent(jButton1)
                            .addComponent(lens))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m5)
                .addGap(18, 18, 18)
                .addComponent(m10)
                .addGap(18, 18, 18)
                .addComponent(lens)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(displayPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 280));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mesures de similarité", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 3, 14))); // NOI18N

        buttonGroup2.add(adamic);
        adamic.setText("Adamic adar");

        buttonGroup2.add(attach);
        attach.setText("Preferential Attachment");

        buttonGroup2.add(jaccard);
        jaccard.setText("Jaccard");

        power.setText("Power Recommandation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(power)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jaccard)
                        .addComponent(adamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adamic)
                .addGap(18, 18, 18)
                .addComponent(attach)
                .addGap(18, 18, 18)
                .addComponent(jaccard)
                .addGap(18, 18, 18)
                .addComponent(power)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 11, 360, 190));

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 113, -1));

        jButton3.setText("Prediction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 710, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
                
         menu m =new menu();
         m.setVisible(true);
         m.setTitle("Menu");
         m.setLocation(350,100);
       
       dispose();
        

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     JFileChooser jf=new JFileChooser();
        int egy =jf.showOpenDialog(this);
        if (egy==javax.swing.JFileChooser.APPROVE_OPTION){ 
             java.io.File file =jf.getSelectedFile();
             String file_name = file.toString( );
             displayPath.setText(file_name);
     }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      /*  if(m5.isSelected() && adamic.isSelected()){
                 double [][] m=new double[5][5];
                   m=Matrices.matrix5;   
                   
        }
        
        if(m5.isSelected() && jaccard.isSelected()){
             double [][] m=new double[5][5];
            BipartiGraph.mat(Matrices.matrix5, 5, 5);
        }        */
        
        if(m5.isSelected() && power.isSelected()){
            double [][] m=new double[5][5];
              m=Matrices.matrix5;   
            BipartiGraph.mat(m, 5, 5);
        }

       /* if(m5.isSelected() && attach.isSelected()){
            BipartiGraph.mat(Matrices.matrix5, 5, 5);
        }

        if(m10.isSelected() && adamic.isSelected()){
            BipartiGraph.mat(Matrices.matrix5, 10, 10);
        }

        if(m10.isSelected() && jaccard.isSelected()){
            BipartiGraph.mat(Matrices.matrix10, 10, 10);
        }

        if(m10.isSelected() && attach.isSelected()){
            BipartiGraph.mat(Matrices.matrix10, 10, 10);
        }   
        
        if(m10.isSelected() && power.isSelected()){
            BipartiGraph.mat(Matrices.matrix10, 10, 10);
        } 
        
        if(lens.isSelected() && adamic.isSelected()){
            BipartiGraph.mat(Matrices.matrixLens, 901, 1683);
        }        
        
        if(lens.isSelected() && adamic.isSelected()){
            BipartiGraph.mat(Matrices.matrixLens, 901, 1683);
        }

        if(lens.isSelected() && adamic.isSelected()){
            BipartiGraph.mat(Matrices.matrixLens, 901, 1683);
        }

        if(lens.isSelected() && adamic.isSelected()){
            BipartiGraph.mat(Matrices.matrixLens, 901, 1683);
        }        */
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adamic;
    private javax.swing.JRadioButton attach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField displayPath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jaccard;
    private javax.swing.JRadioButton lens;
    private javax.swing.JRadioButton m10;
    private javax.swing.JRadioButton m5;
    private javax.swing.JRadioButton power;
    // End of variables declaration//GEN-END:variables
}
